{{- include "pinglib.configmap" (list . "admin-portal") -}}


{{- define "admin-portal.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  {{ include "global.private.host.port" (list $top $v "REACT_APP_API" "api") }}
  {{ include "global.public.host.port" (list $top $v "REACT_APP_API" "api") }}
{{- end -}}