apiVersion: v2
name: skdev
description: Deploy an sk dev environment

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This matches the version of `ping-devops` this chart depends on 
appVersion: "0.7.8"

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: ping-devops
  version: 0.7.8
  repository: https://helm.pingidentity.com
  import-values:
    - child: global
      parent: global